title: Michel Neeser

collections:
  sections:
    output: true
    permalink: /:name/
    order:
      - romane.md
      - sachbuecher-bios.md
      - bitcoin.md
      - effekte-gesetze.md
      - nostalgische-websites.md
      - tipps-tricks.md
      - about.md

defaults:
  - scope:
      type: "sections"
    values:
      layout: "section"
