title: Michel Neeser
url: https://www.michelneeser.ch

collections:
  sections:
    output: true
    permalink: /:name/
    order:
      - blog.md
      - gemischte-linksammlung.md
      - agile-scrum.md
      - romane.md
      - sachbuecher-bios.md
      - effekte-gesetze.md
      - tipps-tricks.md
      - nostalgische-websites.md
      - crypto-bitcoin.md
      - about.md
  posts:
    permalink: /blog/:title/

defaults:
  - scope:
      type: "sections"
    values:
      layout: "section"
  - scope:
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-target-blank
